config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root      'meadows#index'
  resources :meadows
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  get       'sessions/new'
  get       '/home',              to: 'static_pages#home'
  get       '/help',              to: 'static_pages#help'
  get       '/signup',            to: 'users#new'
  get       '/login',             to: 'sessions#new'
  post      '/login',             to: 'sessions#create'
  delete    '/logout',            to: 'sessions#destroy'
end

app/models/meadow.rb
class Meadow < ApplicationRecord
  belongs_to :user
  validates :name, presence: true,
                   length: { minimum: 3 }
  validates :description, presence: true,
                          length: { minimum: 10 }
  validates :user_id, presence: true
end

app/controllers/meadows_controller.rb
class MeadowsController < ApplicationController
  before_action :set_meadow, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  # GET /meadows
  # GET /meadows.json
  def index
    @meadows = Meadow.all.paginate(page: params[:page])
  end

  # GET /meadows/1
  # GET /meadows/1.json
  def show
  end

  # GET /meadows/new
  def new
    @meadow = Meadow.new
  end

  # GET /meadows/1/edit
  def edit
  end

  # POST /meadows
  # POST /meadows.json
  def create
    @meadow = current_user.meadows.build(meadow_params)

    respond_to do |format|
      if @meadow.save
        format.html { redirect_to @meadow, notice: 'Meadow was successfully created.' }
        format.json { render :show, status: :created, location: @meadow }
      else
        format.html { render :new }
        format.json { render json: @meadow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meadows/1
  # PATCH/PUT /meadows/1.json
  def update
    respond_to do |format|
      if @meadow.update(meadow_params)
        format.html { redirect_to @meadow, notice: 'Meadow was successfully updated.' }
        format.json { render :show, status: :ok, location: @meadow }
      else
        format.html { render :edit }
        format.json { render json: @meadow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meadows/1
  # DELETE /meadows/1.json
  def destroy
    @meadow.destroy
    flash[:success] = "Meadow deleted"
    redirect_to request.referrer || meadows_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meadow
      @meadow = Meadow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meadow_params
      params.require(:meadow).permit(:name, :description)
    end

    def correct_user
      @meadow = current_user.meadows.find_by(id: params[:id])
      redirect_to root_url if @meadow.nil?
    end
end

app/helpers/meadows_helper.rb
module MeadowsHelper
end

app/views/meadows/_form.html.erb
<%= form_with(model: meadow, local: true) do |form| %>
  <% if meadow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meadow.errors.count, "error") %> prohibited this meadow from being saved:</h2>

      <ul>
      <% meadow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meadows/_meadow.html.erb
<div class="meadow">
  <span class="name"><%= meadow.name %></span>
  <span class="description"><%= meadow.description %></span>
  <span class="timestamp">Created <%= time_ago_in_words(meadow.created_at) %> ago</span>
  <span class="user">
    <%= link_to meadow.user.name, meadow.user %>
  </span>
  <span><%= link_to 'Show', meadow %></span>
</tr>

app/views/meadows/edit.html.erb
<%= link_to 'Back', meadows_path %>

<h1>Editing Meadow</h1>

<%= render 'form', meadow: @meadow %>

<%= link_to 'Show', @meadow %> |
<%= link_to 'Back', meadows_path %>

app/views/meadows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meadows</h1>

<%= will_paginate %>

<div>
  <div>
      <span>Name</span>
      <span>Description</span>
  </div>

  <div class="meadows">
    <%= render @meadows %>
  </div>
</div>

<%= will_paginate %>

<%= link_to 'New Meadow', new_meadow_path %>

app/views/meadows/new.html.erb
<h1>New Meadow</h1>

<%= render 'form', meadow: @meadow %>

<%= link_to 'Back', meadows_path %>

app/views/meadows/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @meadow.name %>
</h1>

<p>
  <%= @meadow.description %>
</p>

<span class="timestamp">Created <%= time_ago_in_words(@meadow.created_at) %> ago</span>
<span class="user">
  <%= link_to @meadow.user.name, @meadow.user %>
</span>

<% if logged_in? %>
  <span><%= link_to 'Edit', edit_meadow_path(@meadow) %></span>
<% end %>
<% if logged_in? && current_user.admin? %>
  <span><%= link_to 'Destroy', @meadow, method: :delete, data: { confirm: 'Are you sure?' } %></span>
<% end %>
<%= link_to 'Back', meadows_path %>